### ISSUE TITLE
The checkbox for global search is always checked

### ISSUE THREAD

**Issue by oliver-graetz** [Rookiestyle/GlobalSearch#9]
## Overview
The checkbox in the search window doesn't remember its state. All the other checkboxes do remember their state.

## Steps to Reproduce
1. Open the search window
2. Uncheck global search and close the window
3. Re-open the search window

## Expected Behavior
The option for global search should still be unchecked.

## Actual Behavior
The option is always checked.

## Context
KeePass Version: 2.47
Plugin Version: 0.7.2

**Comment by Rookiestyle** [comment]
In the search form, the checkbox' state depends on the plugin's configuration. The configuration can be changed in Tools - Options - Plugin Options - GlobalSearch

You can override this for a specific search directly in the search form. If you want this to be a permanent change, please change it in the plugin's configuration.
This is based on the assumption that you in general want to do a global search

**Comment by Rookiestyle** [comment]
I need to have a closer look

**Comment by Rookiestyle** [comment]
The checkbox for global search is not displayed at all if this configuration option is inactive.

I'll release a fix that will change the plugin as follows.

**As-Is**
Do NOT show the checkbox in the search form if less then 2 databases are open
Do NOT show the checkbox if disabled in the plugin config
If shown, show it as ticked
Ticking/Unticking the checkbox in the search form does not update the plugin config

**To-Be**
Always show the checkbox in the search form if at least 2 databases are open
If enabled in the plugin config, tick the checkbox and leave it unticked otherwise
Ticking/Unticking the checkbox in the search form does not update the plugin config

This way you can define the default behaviour in the plugin configuration and you can override it in case you exceptionally need to search in a different way.
To change the general / default behaviour, you still have to change the plugin config.

**Comment by oliver-graetz** [comment]
> In the search form, the checkbox' state depends on the plugin's configuration. The configuration can be changed in Tools - Options - Plugin Options - GlobalSearch

I looked there and disabling it for the search window completely removed the checkbox instead of toggling its state. That was not what I was looking for.

>  This is based on the assumption that you in general want to do a global search

Until you don't. And once you don't, then the assumption should be that you could want to do several searches on only one of the databases in a short amount of time. That's the whole rationale behind keeping the state of a checkbox between uses. All the other checkboxes in the search window behave in this way and frankly, it's always a good idea to adhere to established behaviour.

It's not as if I just stumbled upon this usability issue by accident. I was actually using for a specific password in just one of the databases and there were several possible variations of the search term, with me being too lazy to write that up as a regex. I got annoyed because I had to uncheck the checkbox upon every opening of the search window.

> If enabled in the plugin config, tick the checkbox and leave it unticked otherwise
Ticking/Unticking the checkbox in the search form does not update the plugin config

This still suggests that there will be a predefined state for the checkbox when opening the search window. Always showing the checkbox is a good idea, and using the config to define the first checked/unchecked state is also good. But once the user changes the state in the window, this should be tracked and remembered until quitting the program.

**Comment by Rookiestyle** [comment]
I tend to disagree out of two reasons

1. Different approach
Changing a checkbox' state is remembered until KeePass is closed and this makes sense as there is no other way to define a default value. 
GlobalSearch can be configured and default values can be set. These default values should then be used and if required be overriden on a per-use basis.
I don't think these two approaches can be compared.

2. (In)consistency
KeePass remembers a changed checkbox all the time, even if you cancel the search form and do not perform a search.
I consider this to be inconsistent, why should the program remember changed search settings if I deliberately decide to not search this way?
In addition, I expect this to cause confusion: Why am I as user able to define a default setting if this default is only valid for the very first time I run a search?

From my point of view, following your consistency arguments would mean:
* Remove this configuration option and go for a "hard coded" default instead
* Cause inconsistency because some plugin settings can be changed permanently and some others don't
* Remember a checkbox setting that has been explicitly discarded even the search form is cancelled/closed

**Comment by oliver-graetz** [comment]
**Regarding 1:** It's okay if there is a possibility to always set the state to the configured value when opening the search. However, it is very common to have such options remember their last used state, not only in KeePass but pretty much universally around applications.

My suggestion: I don't think it makes much sense to completely not offer global search in any context. So the config should not be whether to activate the function in window XY but whether to have it activated. And this could be changed from a checkbox in the config to a select with _"always off"_/_"always on"_/_"remember last used state"_. When using the third option then I don't care how it is initialized, but it should remember the used state whenever closing the respective window, even when exiting KeePass.

**Regarding 2:** I was also a bit shocked that the other checkboxes even remember their state when clicking "Cancel". This I consider wrong, just as you do. I was however inclined to put consistency with the rest of the program before doing what I myself consider to be the right thing to do. This is kind of the Windows way. The Linux way would be to do the right thing and on top of that escalate the perceived false behaviour to the KeePass core developer. I'm generally okay with both approaches.

**Comment by oliver-graetz** [comment]
Also, I have had some exceptions thrown at me when testing the plugin. However, with a new release incoming I don't know if it makes sense to create a bug report for the current version.

**Comment by Rookiestyle** [comment]
Ticking/Unticking the "Search in all open databases" checkbox is now remembered per session/until KeePass is closed which matches the behaviour of the KeePass standard search checkboxes.

You can still use the plugin's configuration to define the initial state after KeePass started.
Changing this configuration will update the above-mentioned session specific setting as well.

I published this as a pre-release: https://github.com/Rookiestyle/GlobalSearch/releases/tag/v0.8
If you still experience exceptions, please let me know.
